export type TenantActionType =
  | "BOOKING_PROVIDER_AND_SERVICES"
  | "BOOKING_DATE_TIME"
  | "BOOKING_APPOINTMENT"
  | "BOOKING_APPOINTMENT_SUCCESS"
  | "BOOKING_APPOINTMENT_FAILURE"
  | "GETTING_TENANT_BY_ID"
  | "GETTING_TENANT_BY_ID_SUCCESS"
  | "GETTING_TENANT_BY_ID_FAILURE";

const BOOKING_APPOINTMENT: TenantActionType = "BOOKING_APPOINTMENT";
const BOOKING_APPOINTMENT_SUCCESS: TenantActionType =
  "BOOKING_APPOINTMENT_SUCCESS";
const BOOKING_APPOINTMENT_FAILURE: TenantActionType =
  "BOOKING_APPOINTMENT_FAILURE";
const BOOKING_PROVIDER_AND_SERVICES: TenantActionType =
  "BOOKING_PROVIDER_AND_SERVICES";
const BOOKING_DATE_TIME: TenantActionType = "BOOKING_DATE_TIME";

const GETTING_TENANT_BY_ID: TenantActionType = "GETTING_TENANT_BY_ID";
const GETTING_TENANT_BY_ID_SUCCESS: TenantActionType = "GETTING_TENANT_BY_ID_SUCCESS";
const GETTING_TENANT_BY_ID_FAILURE: TenantActionType = "GETTING_TENANT_BY_ID_FAILURE";

export {
  BOOKING_PROVIDER_AND_SERVICES,
  BOOKING_DATE_TIME,
  BOOKING_APPOINTMENT,
  BOOKING_APPOINTMENT_SUCCESS,
  BOOKING_APPOINTMENT_FAILURE,

  GETTING_TENANT_BY_ID,
  GETTING_TENANT_BY_ID_SUCCESS,
  GETTING_TENANT_BY_ID_FAILURE,
};
