export type EventActionType =
  | "BOOKING_PROVIDER_AND_SERVICES"
  | "BOOKING_DATE_TIME"
  | "BOOKING_APPOINTMENT"
  | "BOOKING_APPOINTMENT_SUCCESS"
  | "BOOKING_APPOINTMENT_FAILURE";

const BOOKING_APPOINTMENT: EventActionType = "BOOKING_APPOINTMENT";
const BOOKING_APPOINTMENT_SUCCESS: EventActionType =
  "BOOKING_APPOINTMENT_SUCCESS";
const BOOKING_APPOINTMENT_FAILURE: EventActionType =
  "BOOKING_APPOINTMENT_FAILURE";
const BOOKING_PROVIDER_AND_SERVICES: EventActionType =
  "BOOKING_PROVIDER_AND_SERVICES";
const BOOKING_DATE_TIME: EventActionType = "BOOKING_DATE_TIME";

export {
  BOOKING_PROVIDER_AND_SERVICES,
  BOOKING_DATE_TIME,
  BOOKING_APPOINTMENT,
  BOOKING_APPOINTMENT_SUCCESS,
  BOOKING_APPOINTMENT_FAILURE,
};
